spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blurb_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: charlie
    password: 1331
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    #    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    hibernate:
      ddl-auto: create
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3276547538782F413F4428472B4B6945025367566B5970
      expiration: 86400000 # a day

